sudo: false
language: c

env:
  global:
    - LUAROCKS=2.4.4
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.4)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

install:
  - source .travis/setenv_lua.sh
  - luarocks install luacov-coveralls

script:
  - lua -v
  - make LUA=lua && make coverage LUA=lua

after_success:
  - luacov-coveralls -v --include %./minify.lua

# turn off email notifications
notifications:
  - email: false
